[server]
# port = 8501 # Commented out to let Cloud decide
# headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00d4ff"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#ffffff"
